name: Validation Workflow
on:
  repository_dispatch:
    types: [workflow_success]
    
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Clone/Fetch File from Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.source_repo }}
          path: contracts                      
          token: ${{ secrets.REPO_READ_TOKEN }}            
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify the Python version you want

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi     
          
      - name: Run Python Script with Input File
        run: |
          find contracts -maxdepth 1 -type f \( -name "*.yaml" -o -name "*.yml" \) -print0 |
          while IFS= read -r -d '' file; do
            echo "Processing: $file"
            PYTHON_SCRIPT_INPUT_PATH="$file"      
            python scripts/validate-odcs-template.py "$PYTHON_SCRIPT_INPUT_PATH" 
          done

      - name: Trigger publish-contract
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_READ_TOKEN }}
          repository: ${{ github.event.client_payload.source_repo }}
          event-type: publish-contract_trigger
          client-payload: |
            {
              "source_repos": "${{ github.event.client_payload.source_repo }}"
            }

